//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditPreAssignedPosition {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditPreAssignedPosition() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EditPreAssignedPosition", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσθήκη Σχολών/Τμημάτων.
        /// </summary>
        internal static string AddAcademics {
            get {
                return ResourceManager.GetString("AddAcademics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Να γίνει προσβάσιμη από όλες τις Σχολές.
        /// </summary>
        internal static string AvailableToAllAcademics {
            get {
                return ResourceManager.GetString("AvailableToAllAcademics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στοιχεία Επικοινωνίας.
        /// </summary>
        internal static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η θέση μπορεί να επιλεγεί από φοιτητές οποιασδήποτε Σχολής/Τμήματος.
        /// </summary>
        internal static string IsAvailableToAllAcademics {
            get {
                return ResourceManager.GetString("IsAvailableToAllAcademics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επειδή η Θέση Πρακτικής έχει προδεσμευτεί από Γραφείο Πρακτικής και έχετε δηλώσει ότι είναι προσβάσιμη από όλες τις Σχολές/Τμήματα δεν μπορείτε να τροποποιήσετε τα στοιχεία της, πέραν από το ον/μο επόπτη, το e-mail επόπτη και του τηλεφώνου επικοινωνίας..
        /// </summary>
        internal static string Reminder1 {
            get {
                return ResourceManager.GetString("Reminder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αν υπάρχουν επιπλέον θέσεις του συγκεκριμένου group που δεν έχουν ακόμα προδεσμευτεί ή αν θέλετε τυχόν προδεσμευμένες θέσεις που θα απελευθερωθούν από τα Γραφεία Πρακτικής να μην είναι πλέον διαθέσιμες, μπορείτε να τις αποσύρετε επιλέγοντας το κουμπί &quot;Απόσυρση Θέσεων&quot;..
        /// </summary>
        internal static string Reminder2 {
            get {
                return ResourceManager.GetString("Reminder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επειδή η θέση πρακτικής άσκησης έχει προδεσμευτεί από Γραφείο Πρακτικής δεν μπορείτε να τροποποιήσετε τα στοιχεία της θέσης παρά μόνο το ον/μο επόπτη, το e-mail επόπτη, το τηλεφώνο επικοινωνίας καθώς και να προσθέσετε Σχολές/Τμήματα από τα οποία θέλετε να είναι προσβάσιμη..
        /// </summary>
        internal static string Reminder3 {
            get {
                return ResourceManager.GetString("Reminder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απόσυρση Θέσεων.
        /// </summary>
        internal static string RevokePosition {
            get {
                return ResourceManager.GetString("RevokePosition", resourceCulture);
            }
        }
    }
}
