//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailVerificationInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailVerificationInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EmailVerificationInfo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατά την εγγραφή σας στην εφαρμογή, σας στάλθηκε e-mail πιστοποίησης με τίτλο:.
        /// </summary>
        internal static string EmailVerification1 {
            get {
                return ResourceManager.GetString("EmailVerification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ΥΠ.Π.Ε.Θ. - ΠΡΑΚΤΙΚΗ ΑΣΚΗΣΗ] Οδηγίες Πιστοποίησης E-mail Λογαριασμού.
        /// </summary>
        internal static string EmailVerification2 {
            get {
                return ResourceManager.GetString("EmailVerification2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εάν το έχετε λάβει , πατήστε το link που έχει στο κείμενό του, ώστε να πιστοποιήσετε το e-mail του λογαριασμού σας. Εάν δεν το έχετε λάβει μπορεί να έχουν συμβεί τα εξής:.
        /// </summary>
        internal static string EmailVerification3 {
            get {
                return ResourceManager.GetString("EmailVerification3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Να μην έχετε δηλώσει σωστά το e-mail σας. Πηγαίνετε στη σελίδα «Στοιχεία Χρήστη» για να δείτε το e-mail που έχετε δηλώσει και, εάν έχετε κάνει λάθος να το διορθώσετε. Μόλις το διορθώσετε, θα σας έρθει νέο e-mail πιστοποίησης..
        /// </summary>
        internal static string EmailVerification4 {
            get {
                return ResourceManager.GetString("EmailVerification4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το e-mail πιστοποίησης που σας στάλθηκε, να έχει μαρκαριστεί ως SPAM και να έχει καταλήξει στην Ανεπιθύμητη Αλληλογραφία του γραμματοκιβωτίου σας. Ψάξτε, λοιπόν, στον φάκελο της Ανεπιθύμητης Αλληλογραφίας (Junk). Σε αυτήν την περίπτωση, να έχετε υπόψη σας ότι κάθε e-mail που σας στέλνει η εφαρμογή θα καταλήγει στην Ανεπιθύμητη Αλληλογραφία σας. Για να το αποφύγετε αυτό, μπορείτε να ορίσετε ένα διαφορετικό e-mail λογαριασμό (εφόσον διαθέτετε) που να μην μαρκάρει τα e-mail της εφαρμογής ως Ανεπιθύμητη Αλληλογ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailVerification5 {
            get {
                return ResourceManager.GetString("EmailVerification5", resourceCulture);
            }
        }
    }
}
