//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Filter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Filter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Filter", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πόλη:.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χώρα:.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τρόπος δημιουργίας:.
        /// </summary>
        internal static string CreationType {
            get {
                return ResourceManager.GetString("CreationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τμήμα:.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κωδικός Group:.
        /// </summary>
        internal static string GroupID {
            get {
                return ResourceManager.GetString("GroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μη εμφάνιση θέσεων που έχουν ολοκληρωθεί:.
        /// </summary>
        internal static string HideCompleted {
            get {
                return ResourceManager.GetString("HideCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ίδρυμα:.
        /// </summary>
        internal static string Institution {
            get {
                return ResourceManager.GetString("Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Καλλικρατικός Δήμος:.
        /// </summary>
        internal static string KaliClity {
            get {
                return ResourceManager.GetString("KaliClity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φυσικό αντικείμενο:.
        /// </summary>
        internal static string PhysicalObject {
            get {
                return ResourceManager.GetString("PhysicalObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κωδικός Θέσης:.
        /// </summary>
        internal static string PositionID {
            get {
                return ResourceManager.GetString("PositionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατάσταση Θέσης:.
        /// </summary>
        internal static string PositionStatus {
            get {
                return ResourceManager.GetString("PositionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιφερειακή Ενότητα:.
        /// </summary>
        internal static string Prefecture {
            get {
                return ResourceManager.GetString("Prefecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τμήμα για το οποίο έγινε η προδέσμευση:.
        /// </summary>
        internal static string PressignedDepartment {
            get {
                return ResourceManager.GetString("PressignedDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ίδρυμα που την προδέσμευσε:.
        /// </summary>
        internal static string PressignedInstitution {
            get {
                return ResourceManager.GetString("PressignedInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eμφάνιση θέσεων που έχουν αποσυρθεί:.
        /// </summary>
        internal static string Revoked {
            get {
                return ResourceManager.GetString("Revoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φίλτρα Αναζήτησης.
        /// </summary>
        internal static string SearchFilters {
            get {
                return ResourceManager.GetString("SearchFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατάσταση:.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα φοιτητή:.
        /// </summary>
        internal static string StudentFirstName {
            get {
                return ResourceManager.GetString("StudentFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επώνυμο φοιτητή:.
        /// </summary>
        internal static string StudentLastName {
            get {
                return ResourceManager.GetString("StudentLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αρ. Μητρώου.
        /// </summary>
        internal static string StudentNumber {
            get {
                return ResourceManager.GetString("StudentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τίτλος:.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
