//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalProvider {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalProvider() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalProvider", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όλα.
        /// </summary>
        internal static string AllAcademics {
            get {
                return ResourceManager.GetString("AllAcademics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όλα.
        /// </summary>
        internal static string AllInstitutions {
            get {
                return ResourceManager.GetString("AllInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσθήκη Θέσης Πρακτικής Άσκησης.
        /// </summary>
        internal static string Button_AddPosition {
            get {
                return ResourceManager.GetString("Button_AddPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επεξήγηση Χρωμάτων.
        /// </summary>
        internal static string Button_Color {
            get {
                return ResourceManager.GetString("Button_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εξαγωγή σε Excel.
        /// </summary>
        internal static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εξαγωγή σε Excel Θέσεων Παραρτημάτων.
        /// </summary>
        internal static string Button_ExportUsers {
            get {
                return ResourceManager.GetString("Button_ExportUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αναζήτηση.
        /// </summary>
        internal static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσοχή: το πλήκτρο Caps Lock είναι πατημένο.
        /// </summary>
        internal static string CapsWarning {
            get {
                return ResourceManager.GetString("CapsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τμήμα.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τμήματα.
        /// </summary>
        internal static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απο Φορέα Υποδοχής.
        /// </summary>
        internal static string DropDownCreationTypeFYPA {
            get {
                return ResourceManager.GetString("DropDownCreationTypeFYPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απο Γραφείο Πρακτικής.
        /// </summary>
        internal static string DropDownCreationTypeGPA {
            get {
                return ResourceManager.GetString("DropDownCreationTypeGPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- αδιάφορο --.
        /// </summary>
        internal static string DropDownIndifferent {
            get {
                return ResourceManager.GetString("DropDownIndifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λήξη.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τρόπος Χρηματοδότησης.
        /// </summary>
        internal static string FundingType {
            get {
                return ResourceManager.GetString("FundingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ακύρωση.
        /// </summary>
        internal static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κλείσιμο.
        /// </summary>
        internal static string Global_Close {
            get {
                return ResourceManager.GetString("Global_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Συνέχεια.
        /// </summary>
        internal static string Global_Continue {
            get {
                return ResourceManager.GetString("Global_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραφή.
        /// </summary>
        internal static string Global_Delete {
            get {
                return ResourceManager.GetString("Global_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όχι.
        /// </summary>
        internal static string Global_No {
            get {
                return ResourceManager.GetString("Global_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προηγούμενο Βήμα.
        /// </summary>
        internal static string Global_Previous {
            get {
                return ResourceManager.GetString("Global_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιστροφή.
        /// </summary>
        internal static string Global_Return {
            get {
                return ResourceManager.GetString("Global_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποθήκευση.
        /// </summary>
        internal static string Global_Save {
            get {
                return ResourceManager.GetString("Global_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποθήκευση &amp; Συνέχεια.
        /// </summary>
        internal static string Global_SaveNContinue {
            get {
                return ResourceManager.GetString("Global_SaveNContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλογή.
        /// </summary>
        internal static string Global_Select {
            get {
                return ResourceManager.GetString("Global_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποστολή.
        /// </summary>
        internal static string Global_Send {
            get {
                return ResourceManager.GetString("Global_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ενημέρωση.
        /// </summary>
        internal static string Global_Update {
            get {
                return ResourceManager.GetString("Global_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ναι.
        /// </summary>
        internal static string Global_Yes {
            get {
                return ResourceManager.GetString("Global_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ίδρυμα.
        /// </summary>
        internal static string Institustion {
            get {
                return ResourceManager.GetString("Institustion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σύστημα Κεντρικής Υποστήριξης της Πρακτικής Άσκησης&lt;br /&gt;Φοιτητών ΑΕΙ.
        /// </summary>
        internal static string MainHeader {
            get {
                return ResourceManager.GetString("MainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Έναρξη.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
    }
}
