//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JavaScriptResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JavaScriptResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.JavaScriptResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το μήκος των χαρακτήρων πρέπει να είναι ακριβώς .
        /// </summary>
        internal static string Botshield_Validation {
            get {
                return ResourceManager.GetString("Botshield_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el.
        /// </summary>
        internal static string Datepicker_Regional {
            get {
                return ResourceManager.GetString("Datepicker_Regional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ακύρωση.
        /// </summary>
        internal static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όχι.
        /// </summary>
        internal static string Global_No {
            get {
                return ResourceManager.GetString("Global_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ χρησιμοποιήστε μόνο λατινικούς χαρακτήρες..
        /// </summary>
        internal static string Imis_Lib_DisableGreekKeyPress {
            get {
                return ResourceManager.GetString("Imis_Lib_DisableGreekKeyPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιτρέπονται μόνο λατινικοί χαρακτήρες χωρίς κενά!.
        /// </summary>
        internal static string Imis_Lib_NoGreekCharacters {
            get {
                return ResourceManager.GetString("Imis_Lib_NoGreekCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλέξατε να αποσύρετε προδεσμευμένη θέση πρακτικής άσκησης.\n\nΕάν αποσύρετε τη θέση, οι επιπλέον θέσεις του συγκεκριμένου group που δεν έχουν ακόμα προδεσμευτεί ή τυχόν προδεσμευμένες θέσεις που θα απελευθερωθούν από τα Γραφεία Πρακτικής δε θα είναι πλέον διαθέσιμες.\n\nΤονίζεται ότι ΔΕΝ είναι δυνατή η επαναφορά της θέσης μετά την Απόσυρση.\n\nΕίστε σίγουροι ότι θέλετε να αποσύρετε τη θέση;.
        /// </summary>
        internal static string InternshipPositions_Cancel {
            get {
                return ResourceManager.GetString("InternshipPositions_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πατώντας το κουμπί Κλωνοποίηση θα δημιουργηθεί μια πανομοιότυπη θέση Πρακτικής Άσκησης την οποία μπορείτε στη συνέχεια να επεξεργαστείτε.\n\nΣε περίπτωση που δεν πρόκειται να τροποποιήσετε κανένα στοιχείο της θέσης που θα δημιουργηθεί σας προτρέπουμε να πατήσετε Ακύρωση και να αλλάξετε τον αριθμό των διαθέσιμων θέσεων της ήδη υπάρχουσας θέσης.\n\nΕίστε σίγουροι ότι θέλετε να κλωνοποιήσετε τη συγκεκριμένη θέση Πρακτικής Άσκησης;.
        /// </summary>
        internal static string InternshipPositions_Clone {
            get {
                return ResourceManager.GetString("InternshipPositions_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουροι ότι θέλετε να διαγράψετε τη συγκεκριμένη θέση πρακτικής άσκησης;.
        /// </summary>
        internal static string InternshipPositions_Delete {
            get {
                return ResourceManager.GetString("InternshipPositions_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μέγιστο μέγεθος {0} χαρακτήρες, έχετε ήδη εισάγει {1}.
        /// </summary>
        internal static string MemoEdit_Info {
            get {
                return ResourceManager.GetString("MemoEdit_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η επικόλληση του κειμένου δε θα ολοκληρωθεί, διότι το κείμενο που προσπαθείτε να εισάγετε υπερβαίνει το επιτρεπόμενο όριο χαρακτήρων..
        /// </summary>
        internal static string MemoEdit_UpdateCounter {
            get {
                return ResourceManager.GetString("MemoEdit_UpdateCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουροι ότι θέλετε να διαγράψετε το συγκρεκριμένο χρήστη;.
        /// </summary>
        internal static string OfficeUsers_Delete {
            get {
                return ResourceManager.GetString("OfficeUsers_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουροι ότι θέλετε να απενεργοποιήσετε το συγκρεκριμένο χρήστη;.
        /// </summary>
        internal static string OfficeUsers_Lock {
            get {
                return ResourceManager.GetString("OfficeUsers_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουροι ότι θέλετε να επανενεργοποιήσετε το συγκρεκριμένο χρήστη;.
        /// </summary>
        internal static string OfficeUsers_Unlock {
            get {
                return ResourceManager.GetString("OfficeUsers_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αριθμός Ταυτότητας.
        /// </summary>
        internal static string ProviderInput_ProviderIdNumber {
            get {
                return ResourceManager.GetString("ProviderInput_ProviderIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αριθμός Διαβατηρίου.
        /// </summary>
        internal static string ProviderInput_ProviderPassNumber {
            get {
                return ResourceManager.GetString("ProviderInput_ProviderPassNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουροι ότι θέλετε να αφαιρέσετε τον αντιστοιχισμένο φοιτητή;.
        /// </summary>
        internal static string SelectedPositions_DeleteAssignment {
            get {
                return ResourceManager.GetString("SelectedPositions_DeleteAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πατώντας το κουμπί Διαγραφή Αντιστοίχισης διαγράφεται η αντιστοίχιση της θέσης με το φοιτητή και αποδεσμεύεται η θέση.\n\nΣε περίπτωση που θέλετε η θέση να παραμείνει δεσμευμένη και να αλλάξετε τον αντιστοιχισμένο φοιτητή θα πρέπει να επιλέξετε Ακύρωση και από την Επεξεργασία θέσης να επιλέξετε Αλλαγή Επιλεγμένου Φοιτητή.\n\nΕίστε σίγουροι ότι θέλετε να αφαιρέσετε τον αντιστοιχισμένο φοιτητή;.
        /// </summary>
        internal static string SelectedPositions_DeleteAssignment2 {
            get {
                return ResourceManager.GetString("SelectedPositions_DeleteAssignment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πατώντας το κουμπί Διαγραφή Θέσης διαγράφεται η επιλεγμένη ολοκληρωμένη θέση, χωρίς δυνατότητα επαναφοράς.\n\nΕίστε σίγουροι ότι θέλετε να διαγράψετε την ολοκληρωμένη θέση;.
        /// </summary>
        internal static string SelectedPositions_DeleteFinishedPosition {
            get {
                return ResourceManager.GetString("SelectedPositions_DeleteFinishedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουροι ότι θέλετε να επαναφέρετε τη θέση σε κατάσταση &quot;Υπό διενέργεια&quot;;.
        /// </summary>
        internal static string SelectedPositions_RollbackCancellation {
            get {
                return ResourceManager.GetString("SelectedPositions_RollbackCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουροι ότι θέλετε να επαναφέρετε τη θέση σε κατάσταση &quot;Υπό διενέργεια&quot;;.
        /// </summary>
        internal static string SelectedPositions_RollbackCompletion {
            get {
                return ResourceManager.GetString("SelectedPositions_RollbackCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουροι ότι θέλετε να αποδεσμεύσετε τη θέση;.
        /// </summary>
        internal static string SelectedPositions_RollbackPreassignment {
            get {
                return ResourceManager.GetString("SelectedPositions_RollbackPreassignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πατώντας το κουμπί Αποδέσμευση ακυρώνεται η προδέσμευση της θέσης και η θέση παύει να είναι διαθέσιμη προς επιλογή από το Ίδρυμά σας.\n\nΕίστε σίγουροι ότι θέλετε να αποδεσμεύσετε τη θέση;.
        /// </summary>
        internal static string SelectedPositions_RollbackPreassignment2 {
            get {
                return ResourceManager.GetString("SelectedPositions_RollbackPreassignment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουροι ότι θέλετε να αφαιρέσετε τη συγκεκριμένη ποινή;.
        /// </summary>
        internal static string StudentPractice_DeleteBlocked {
            get {
                return ResourceManager.GetString("StudentPractice_DeleteBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προέκυψε ένα σφάλμα κατά την εκτέλεση της ενέργειας! Παρακαλώ προσπαθήστε ξανά..
        /// </summary>
        internal static string StudentPractice_Error {
            get {
                return ResourceManager.GetString("StudentPractice_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν μπορείτε να διαγράψετε το συγκεκριμένο χρήστη, γιατί έχει ήδη απαντήσει σε συμβάντα.\n\nΑν θέλετε ο χρήστης να μην έχει πλέον πρόσβαση στην εφαρμογή μπορείτε να τον απενεργοποιήσετε πατώντας το εικονίδιο με το λουκετάκι κάτω από τη στήλη &quot;Επεξεργασία Χρήστη&quot;.
        /// </summary>
        internal static string StudentPractice_HelpDeskUsers {
            get {
                return ResourceManager.GetString("StudentPractice_HelpDeskUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν μπορείτε να διαγράψετε το συγκεκριμένο χρήστη, γιατί έχει στο παρελθόν κάνει ενέργειες στην εφαρμογή.\n\nΑν θέλετε ο χρήστης να μην έχει πλέον πρόσβαση στην εφαρμογή μπορείτε να τον απενεργοποιήσετε πατώντας το εικονίδιο με το λουκέτο κάτω από τη στήλη &quot;Επεξεργασία Χρήστη&quot;.
        /// </summary>
        internal static string StudentPractice_OfficeUsers {
            get {
                return ResourceManager.GetString("StudentPractice_OfficeUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν μπορείτε να διαγράψετε το συγκεκριμένο χρήστη, γιατί έχει στο παρελθόν κάνει ενέργειες στην εφαρμογή.\n\nΑν θέλετε ο χρήστης να μην έχει πλέον πρόσβαση στην εφαρμογή μπορείτε να τον απενεργοποιήσετε πατώντας το εικονίδιο με το λουκετάκι κάτω από τη στήλη &quot;Επεξεργασία Χρήστη&quot;.
        /// </summary>
        internal static string StudentPractice_ProviderUsers {
            get {
                return ResourceManager.GetString("StudentPractice_ProviderUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλέξατε να αποσύρετε προδεσμευμένη θέση πρακτικής άσκησης.\n\nΕάν αποσύρετε τη θέση, οι επιπλέον θέσεις του συγκεκριμένου group που δεν έχουν ακόμα προδεσμευτεί ή τυχόν προδεσμευμένες θέσεις που θα απελευθερωθούν από τα Γραφεία Πρακτικής δε θα είναι πλέον διαθέσιμες.\n\nΕίστε σίγουροι ότι θέλετε να αποσύρετε τη θέση;.
        /// </summary>
        internal static string StudentPractice_Revoke {
            get {
                return ResourceManager.GetString("StudentPractice_Revoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλέξατε να επαναφέρετε προδεσμευμένη θέση πρακτικής άσκησης.\n\nΕάν επαναφέρετε τη θέση, οι επιπλέον θέσεις του συγκεκριμένου group που δεν έχουν ακόμα προδεσμευτεί ή τυχόν προδεσμευμένες θέσεις που θα απελευθερωθούν από τα Γραφεία Πρακτικής θα είναι πλέον διαθέσιμες.\n\nΕίστε σίγουροι ότι θέλετε να επαναφέρετε τη θέση;.
        /// </summary>
        internal static string StudentPractice_Rollback {
            get {
                return ResourceManager.GetString("StudentPractice_Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλέξατε να επαναφέρετε προδεσμευμένη θέση πρακτικής άσκησης.\n\nΓκρουπ θα επανέλθει σε κατάσταση &quot;Δημοσιευμένο&quot; και όλες οι ακυρωμένες Θέσεις του θα επανέλθουν σε κατάσταση &quot;Ελεύθερες&quot;\n\nΕίστε σίγουροι ότι θέλετε να επαναφέρετε τη θέση;.
        /// </summary>
        internal static string StudentPractice_RollbackPublish {
            get {
                return ResourceManager.GetString("StudentPractice_RollbackPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουροι ότι θέλετε να επαναφέρετε τη θέση;.
        /// </summary>
        internal static string StudentPractice_UndeleteGroup {
            get {
                return ResourceManager.GetString("StudentPractice_UndeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Θέλετε σίγουρα να αλλάξετε τα στοιχεία του γραφείου;.
        /// </summary>
        internal static string StudentPractice_vgEditOffice {
            get {
                return ResourceManager.GetString("StudentPractice_vgEditOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Θέλετε σίγουρα να αλλάξετε τα στοιχεία του φορέα;.
        /// </summary>
        internal static string StudentPractice_vgEditProvider {
            get {
                return ResourceManager.GetString("StudentPractice_vgEditProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αλλαγή Email.
        /// </summary>
        internal static string UserContactDetails_EmailChange {
            get {
                return ResourceManager.GetString("UserContactDetails_EmailChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το email {email} χρησιμοποιείται και δεν μπορεί να πραγματοποιηθεί η αλλαγή..
        /// </summary>
        internal static string UserContactDetails_EmailInUse {
            get {
                return ResourceManager.GetString("UserContactDetails_EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Email {newEmail} δεν είναι έγκυρο.
        /// </summary>
        internal static string UserContactDetails_EmailInvalid {
            get {
                return ResourceManager.GetString("UserContactDetails_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Νέο Email.
        /// </summary>
        internal static string UserContactDetails_EmailNew {
            get {
                return ResourceManager.GetString("UserContactDetails_EmailNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προκλήθηκε σφάλμα. Παρακαλούμε δοκιμάστε ξανά αργότερα..
        /// </summary>
        internal static string UserContactDetails_ErrorMessage {
            get {
                return ResourceManager.GetString("UserContactDetails_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αλλαγή Κινητού.
        /// </summary>
        internal static string UserContactDetails_MobileChange {
            get {
                return ResourceManager.GetString("UserContactDetails_MobileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Κινητό {newMobilePhone} δεν είναι έγκυρο.
        /// </summary>
        internal static string UserContactDetails_MobileInvalid {
            get {
                return ResourceManager.GetString("UserContactDetails_MobileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Έχετε ξεπεράσει τον μέγιστο επιτρεπόμενο αριθμό επαναποστολών του SMS Πιστοποίησης. Παρακαλούμε επικοινωνήστε με το Γραφείο Αρωγής Χρηστών..
        /// </summary>
        internal static string UserContactDetails_MobileLimit {
            get {
                return ResourceManager.GetString("UserContactDetails_MobileLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Νέο Κινητό.
        /// </summary>
        internal static string UserContactDetails_MobileNew {
            get {
                return ResourceManager.GetString("UserContactDetails_MobileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η αλλαγή του κινητού ολοκληρώθηκε επιτυχώς.
        /// </summary>
        internal static string UserContactDetails_MobileSuccess {
            get {
                return ResourceManager.GetString("UserContactDetails_MobileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η αλλαγή ολοκληρώθηκε επιτυχώς και σας στάλθηκε ένα e-mail πιστοποίησης στη διεύθυνση που δηλώσατε.
        /// </summary>
        internal static string UserContactDetails_SuccessMessage {
            get {
                return ResourceManager.GetString("UserContactDetails_SuccessMessage", resourceCulture);
            }
        }
    }
}
