//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PositionPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PositionPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PositionPages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσθήκη Σχολών/Τμημάτων.
        /// </summary>
        internal static string PositionAcademics_AddAcademics {
            get {
                return ResourceManager.GetString("PositionAcademics_AddAcademics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλέξατε ότι θέλετε η θέση πρακτικής άσκησης να είναι προσβάσιμη σε ΟΛΑ τα Τμήματα της επικράτειας.\n\nΕπισημαίνεται ότι περιορίζοντας τη θέση μόνο σε Τμήματα σχετικά με το γνωστικό αντικείμενο της, αυξάνετε τις πιθανότητες επιλογής της.\n\nΕίστε σίγουρος/η ότι θέλετε η θέση να είναι προσβάσιμη από όλες τις σχολές.
        /// </summary>
        internal static string PositionAcademics_ConfirmVisibleToAll {
            get {
                return ResourceManager.GetString("PositionAcademics_ConfirmVisibleToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πρέπει να δηλώσετε τα Τμήματα για τα οποία θέλετε να είναι διαθέσιμη η θέση πρακτικής άσκησης για να μπορέσετε να συνεχίσετε..
        /// </summary>
        internal static string PositionAcademics_Error {
            get {
                return ResourceManager.GetString("PositionAcademics_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κανόνες Πρακτικής Άσκησης Τμημάτων.
        /// </summary>
        internal static string PositionAcademics_OfficeRules {
            get {
                return ResourceManager.GetString("PositionAcademics_OfficeRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιορισμός σε συγκεκριμένες Σχολές/Τμήματα.
        /// </summary>
        internal static string PositionAcademics_RestrictAcademics {
            get {
                return ResourceManager.GetString("PositionAcademics_RestrictAcademics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλέξτε τα Τμήματα για τα οποία θέλετε να είναι προσβάσιμη η θέση.
        /// </summary>
        internal static string PositionAcademics_SelectAcademics {
            get {
                return ResourceManager.GetString("PositionAcademics_SelectAcademics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσβάσιμη από όλες τις Σχολές.
        /// </summary>
        internal static string PositionAcademics_VisibleToAll {
            get {
                return ResourceManager.GetString("PositionAcademics_VisibleToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Έχετε επιλέξει ότι η θέση Πρακτικής Άσκησης είναι προσβάσιμη από φοιτητές όλων των Σχολών/Τμημάτων..
        /// </summary>
        internal static string PositionAcademics_VisibleToAllAcademics1 {
            get {
                return ResourceManager.GetString("PositionAcademics_VisibleToAllAcademics1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αν θέλετε να περιορίσετε τη θέση σε συγκεκριμένες Σχολές/Τμήματα πατήστε το παρακάτω κουμπί..
        /// </summary>
        internal static string PositionAcademics_VisibleToAllAcademics2 {
            get {
                return ResourceManager.GetString("PositionAcademics_VisibleToAllAcademics2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επισημαίνεται ότι περιορίζοντας τη θέση μόνο σε Τμήματα σχετικά με το γνωστικό αντικείμενο της, αυξάνετε τις πιθανότητες επιλογής της..
        /// </summary>
        internal static string PositionAcademics_VisibleToAllAcademics3 {
            get {
                return ResourceManager.GetString("PositionAcademics_VisibleToAllAcademics3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η δημιουργία νέας θέσης δεν είναι διαθέσιμη..
        /// </summary>
        internal static string PositionDetails_CreationNotAllowed {
            get {
                return ResourceManager.GetString("PositionDetails_CreationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μπορείτε να επεξεργαστείτε τη νέα θέση που δημιουργήσατε και, αν υπάρχουν παραπάνω από μία διαθέσιμες θέσεις, να τροποποιήσετε κατάλληλα το πεδίο &apos;Διαθέσιμες Θέσεις&apos;.
        /// </summary>
        internal static string PositionDetails_Note {
            get {
                return ResourceManager.GetString("PositionDetails_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσθήκη Αντικειμένου Θέσης.
        /// </summary>
        internal static string PositionPhysicalObject_Add {
            get {
                return ResourceManager.GetString("PositionPhysicalObject_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πρέπει να προσθέσετε τουλάχιστον ένα γνωστικό αντικείμενο για τη θέση πρακτικής άσκησης για να μπορέσετε να συνεχίσετε..
        /// </summary>
        internal static string PositionPhysicalObject_Error {
            get {
                return ResourceManager.GetString("PositionPhysicalObject_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλέξτε ένα ή περισσότερα αντικείμενα, τα οποία θεωρείτε ότι ταιριάζουν περισσότερο με τη θέση..
        /// </summary>
        internal static string PositionPhysicalObject_Info {
            get {
                return ResourceManager.GetString("PositionPhysicalObject_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η θέση έχει αποθηκευτεί. Ωστόσο δε θα είναι διαθέσιμη στην Αναζήτηση μέχρι να επιλέξετε «Δημοσίευση».
        /// </summary>
        internal static string PositionPreview_FlashMessage {
            get {
                return ResourceManager.GetString("PositionPreview_FlashMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποθήκευση Θέσης.
        /// </summary>
        internal static string PositionPreview_SavePosition {
            get {
                return ResourceManager.GetString("PositionPreview_SavePosition", resourceCulture);
            }
        }
    }
}
