//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PositionGroupInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PositionGroupInput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PositionGroupInput", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σχολές/Τμήματα για τα οποία είναι προσβάσιμη η θέση.
        /// </summary>
        internal static string Academics {
            get {
                return ResourceManager.GetString("Academics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η θέση είναι προσβάσιμη από φοιτητές όλων των Σχολών/Τμημάτων..
        /// </summary>
        internal static string AcademicsAll {
            get {
                return ResourceManager.GetString("AcademicsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πόλη:.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Πόλη&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρατηρήσεις:.
        /// </summary>
        internal static string CompletionComments {
            get {
                return ResourceManager.GetString("CompletionComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημ/νία λήξης πρακτικής:.
        /// </summary>
        internal static string CompletionEndDate {
            get {
                return ResourceManager.GetString("CompletionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στοιχεία Ολοκλήρωσης Πρακτικής Άσκησης.
        /// </summary>
        internal static string CompletionHeader {
            get {
                return ResourceManager.GetString("CompletionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημ/νία έναρξης πρακτικής:.
        /// </summary>
        internal static string CompletionStartDate {
            get {
                return ResourceManager.GetString("CompletionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποτέλεσμα ολοκλήρωσης:.
        /// </summary>
        internal static string CompletionVerdict {
            get {
                return ResourceManager.GetString("CompletionVerdict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τηλέφωνο επικοινωνίας:.
        /// </summary>
        internal static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πρέπει να αποτελείται από τουλάχιστον 3 αριθμούς ή και το προαιρετικό &apos;+&apos; στην αρχή.
        /// </summary>
        internal static string ContactPhoneFrRegex {
            get {
                return ResourceManager.GetString("ContactPhoneFrRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Τηλέφωνο επικοινωνίας&apos; πρέπει να αποτελείται από ακριβώς 10 ψηφία και να ξεκινάει από 2 αν πρόκειται για σταθερό ή από 69 αν πρόκειται για κινητό..
        /// </summary>
        internal static string ContactPhoneGrRegex {
            get {
                return ResourceManager.GetString("ContactPhoneGrRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Τηλέφωνο επικοινωνίας&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string ContactPhoneRequired {
            get {
                return ResourceManager.GetString("ContactPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χώρα:.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Χώρα&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τμήμα:.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιγραφή:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Περιγραφή&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διάρκεια Πρακτικής Άσκησης:.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Διάρκεια Πρακτικής Άσκησης&apos; πρέπει να έχει τιμή μεταξύ 1 και 99.
        /// </summary>
        internal static string DurationRange {
            get {
                return ResourceManager.GetString("DurationRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Διάρκεια Πρακτικής Άσκησης&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string DurationRequired {
            get {
                return ResourceManager.GetString("DurationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημ/νία εκτέλεσης (έως):.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Ημ/νία εκτέλεσης (έως)&apos; δεν είναι έγκυρο.
        /// </summary>
        internal static string EndDateCompare {
            get {
                return ResourceManager.GetString("EndDateCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η &apos;Ημ/νία εκτέλεσης (έως)&apos; πρέπει να είναι μεταγενέστερη της σημερινής και της ημερομηνίας εκτέλεσης (από).
        /// </summary>
        internal static string EndDateCustom {
            get {
                return ResourceManager.GetString("EndDateCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Ημ/νία εκτέλεσης (έως)&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παράδειγμα Συμπληρωμένης Θέσης.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τρόπος Χρηματοδότησης:.
        /// </summary>
        internal static string FundingType {
            get {
                return ResourceManager.GetString("FundingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Γενικά Στοιχεία Θέσης.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στοιχεία Εκτέλεσης Πρακτικής Άσκησης.
        /// </summary>
        internal static string ImplementationHeader {
            get {
                return ResourceManager.GetString("ImplementationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δήμος:.
        /// </summary>
        internal static string Kali_CityCy {
            get {
                return ResourceManager.GetString("Kali_CityCy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- επιλέξτε δήμο --.
        /// </summary>
        internal static string Kali_CityCyPrompt {
            get {
                return ResourceManager.GetString("Kali_CityCyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Δήμος&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string Kali_CityCyRequired {
            get {
                return ResourceManager.GetString("Kali_CityCyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Καλλικρατικός Δήμος:.
        /// </summary>
        internal static string Kali_CityGr {
            get {
                return ResourceManager.GetString("Kali_CityGr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- επιλέξτε καλλικρατικό δήμο --.
        /// </summary>
        internal static string Kali_CityGrPrompt {
            get {
                return ResourceManager.GetString("Kali_CityGrPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Καλλικρατικός Δήμος&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string Kali_CityGrRequired {
            get {
                return ResourceManager.GetString("Kali_CityGrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλω περιμένετε.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αντικείμενο Θέσης.
        /// </summary>
        internal static string PhysicanObject {
            get {
                return ResourceManager.GetString("PhysicanObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημ/νία αντιστοίχισης:.
        /// </summary>
        internal static string PositionAssignedAt {
            get {
                return ResourceManager.GetString("PositionAssignedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η πρακτική ολοκληρώθηκε επιτυχώς.
        /// </summary>
        internal static string PositionCompleted {
            get {
                return ResourceManager.GetString("PositionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αριθμός διαθέσιμων θέσεων:.
        /// </summary>
        internal static string PositionCount {
            get {
                return ResourceManager.GetString("PositionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Αριθμός διαθέσιμων θέσεων&apos; πρέπει να έχει τιμή μεταξύ 1 και 99.
        /// </summary>
        internal static string PositionCountRange {
            get {
                return ResourceManager.GetString("PositionCountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Αριθμός διαθέσιμων θέσεων&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string PositionCountRequired {
            get {
                return ResourceManager.GetString("PositionCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η πρακτική ΔΕΝ ολοκληρώθηκε.
        /// </summary>
        internal static string PositionNotCompleted {
            get {
                return ResourceManager.GetString("PositionNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατάσταση θέσης:.
        /// </summary>
        internal static string PositionStatus {
            get {
                return ResourceManager.GetString("PositionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είδος θέσης:.
        /// </summary>
        internal static string PositionType {
            get {
                return ResourceManager.GetString("PositionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Είδος θέσης&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string PositionTypeRequired {
            get {
                return ResourceManager.GetString("PositionTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- επιλέξτε είδος θέσης --.
        /// </summary>
        internal static string PositionType_ddl {
            get {
                return ResourceManager.GetString("PositionType_ddl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημ/νία προδέσμευσης:.
        /// </summary>
        internal static string PreAssignedAt {
            get {
                return ResourceManager.GetString("PreAssignedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προδεσμευμένες θέσεις:.
        /// </summary>
        internal static string PreassignedPositions {
            get {
                return ResourceManager.GetString("PreassignedPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στοιχεία Προδέσμευσης.
        /// </summary>
        internal static string PreAssignmentHeader {
            get {
                return ResourceManager.GetString("PreAssignmentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προβλεπόμενη ημ/νία λήξης:.
        /// </summary>
        internal static string PredictedEndDate {
            get {
                return ResourceManager.GetString("PredictedEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προβλεπόμενη ημ/νία έναρξης:.
        /// </summary>
        internal static string PredictedStartDate {
            get {
                return ResourceManager.GetString("PredictedStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επαρχία:.
        /// </summary>
        internal static string PrefectureCy {
            get {
                return ResourceManager.GetString("PrefectureCy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- επιλέξτε επαρχία --.
        /// </summary>
        internal static string PrefectureCyPrompt {
            get {
                return ResourceManager.GetString("PrefectureCyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Επαρχία&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string PrefectureCyRequired {
            get {
                return ResourceManager.GetString("PrefectureCyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιφερειακή Ενότητα:.
        /// </summary>
        internal static string PrefectureGr {
            get {
                return ResourceManager.GetString("PrefectureGr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- επιλέξτε περιφερειακή ενότητα --.
        /// </summary>
        internal static string PrefectureGrPrompt {
            get {
                return ResourceManager.GetString("PrefectureGrPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Περιφερειακή Ενότητα&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string PrefectureGrRequired {
            get {
                return ResourceManager.GetString("PrefectureGrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημ/νία εκτέλεσης (από):.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Ημ/νία εκτέλεσης (από)&apos; δεν είναι έγκυρο.
        /// </summary>
        internal static string StartDateCompare {
            get {
                return ResourceManager.GetString("StartDateCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το διάστημα δυνατής εκτέλεσης (Ημ/νία εκτέλεσης από / έως) είναι μικρότερο από τη διάρκεια πρακτικής άσκησης που δηλώσατε.
        /// </summary>
        internal static string StartDateCustom {
            get {
                return ResourceManager.GetString("StartDateCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Ημ/νία εκτέλεσης (από)&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ον/μο Επόπτη:.
        /// </summary>
        internal static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Επόπτη:.
        /// </summary>
        internal static string SupervisorEmail {
            get {
                return ResourceManager.GetString("SupervisorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;E-mail Επόπτη&apos; δεν είναι έγκυρο.
        /// </summary>
        internal static string SupervisorEmailRegex {
            get {
                return ResourceManager.GetString("SupervisorEmailRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαθέσιμη χρονική περίοδος για την εκτέλεση της ΠΑ:.
        /// </summary>
        internal static string TimeLimit {
            get {
                return ResourceManager.GetString("TimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Με χρονικό περιορισμό.
        /// </summary>
        internal static string TimeLimitWith {
            get {
                return ResourceManager.GetString("TimeLimitWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χωρίς χρονικό περιορισμό.
        /// </summary>
        internal static string TimeLimitWithout {
            get {
                return ResourceManager.GetString("TimeLimitWithout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τίτλος:.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Τίτλος&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Συνολικός αριθμός θέσεων:.
        /// </summary>
        internal static string TotalPositions {
            get {
                return ResourceManager.GetString("TotalPositions", resourceCulture);
            }
        }
    }
}
