//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProviderLiterals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProviderLiterals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ProviderLiterals", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπάρχει ήδη πιστοποιημένος λογαριασμός με το Α.Φ.Μ. που δηλώσατε.
        /// </summary>
        internal static string CannotBeVerifiedUser1 {
            get {
                return ResourceManager.GetString("CannotBeVerifiedUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αν πιστεύετε ότι αυτό δεν είναι σωστό, παρακαλούμε επικοινωνήστε με το Γραφείο Αρωγής για να το αναφέρετε.
        /// </summary>
        internal static string CannotBeVerifiedUser2 {
            get {
                return ResourceManager.GetString("CannotBeVerifiedUser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αριθμός Βεβαίωσης.
        /// </summary>
        internal static string CertificationNumber {
            get {
                return ResourceManager.GetString("CertificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Για τις ανάγκες του συγκεκριμένου προγράμματος, το Φορέα εκπροσωπεί ο/η &lt;{0}&gt; με e-mail &lt;{1}&gt; και τηλέφωνο &lt;{2}&gt; του/της οποίου/οποίας αναπληρωτής/αναπληρώτρια είναι ο/η &lt;{3}&gt; με e-mail &lt;{4}&gt; και τηλέφωνο &lt;{5}&gt;. Κάθε πράξη ή παράλειψη του εξουσιοδοτηµένου φυσικού προσώπου θεωρείται πράξη ή παράλειψη του ΦΥΠΑ, ο οποίος και ευθύνεται εξ ολοκλήρου..
        /// </summary>
        internal static string ContactPersonDetails1 {
            get {
                return ResourceManager.GetString("ContactPersonDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Για τις ανάγκες του συγκεκριμένου προγράμματος, το Φορέα εκπροσωπεί ο/η &lt;{0}&gt; με e-mail &lt;{1}&gt; και τηλέφωνο &lt;{2}&gt;. Κάθε πράξη ή παράλειψη του εξουσιοδοτηµένου φυσικού προσώπου θεωρείται πράξη ή παράλειψη του ΦΥΠΑ, ο οποίος και ευθύνεται εξ ολοκλήρου..
        /// </summary>
        internal static string ContactPersonDetails2 {
            get {
                return ResourceManager.GetString("ContactPersonDetails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επισυνάπτεται φωτοτυπία αστυνομικής ταυτότητας του Νομίμου Εκπροσώπου..
        /// </summary>
        internal static string IdentificationCopy1 {
            get {
                return ResourceManager.GetString("IdentificationCopy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επισυνάπτεται φωτοτυπία διαβατηρίου του Νομίμου Εκπροσώπου..
        /// </summary>
        internal static string IdentificationCopy2 {
            get {
                return ResourceManager.GetString("IdentificationCopy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κεντρικός Χρήστης.
        /// </summary>
        internal static string MasterAccount {
            get {
                return ResourceManager.GetString("MasterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Βεβαιώνεται ότι ο Φορέας &lt;{0}&gt; με Α.Φ.Μ. &lt;{1}&gt;, Δ.Ο.Υ. &lt;{2}&gt; του οποίου Νόμιμος Εκπρόσωπος είναι ο/η &lt;{3}&gt; με Α.Δ.Τ. &lt;{4}&gt;, που εκδόθηκε την &lt;{5:dd/MM/yyyy}&gt; στο &lt;{6}&gt;, με τηλέφωνο &lt;{7}&gt; συμμετέχει στο «Σύστημα Κεντρικής Υποστήριξης της Πρακτικής Άσκησης Φοιτητών ΑΕΙ» ως Φορέας Υποδοχής με το username: &lt;{8}&gt;..
        /// </summary>
        internal static string ProviderDetails1 {
            get {
                return ResourceManager.GetString("ProviderDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Βεβαιώνεται ότι ο Φορέας &lt;{0}&gt; με Α.Φ.Μ. &lt;{1}&gt;, Δ.Ο.Υ. &lt;{2}&gt; του οποίου Νόμιμος Εκπρόσωπος είναι ο/η &lt;{3}&gt; με Αριθμό Διαβατηρίου &lt;{4}&gt;, με τηλέφωνο &lt;{5}&gt; συμμετέχει στο «Σύστημα Κεντρικής Υποστήριξης της Πρακτικής Άσκησης Φοιτητών ΑΕΙ» ως Φορέας Υποδοχής με το username: &lt;{6}&gt;..
        /// </summary>
        internal static string ProviderDetails2 {
            get {
                return ResourceManager.GetString("ProviderDetails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν έχετε ακόμη πιστοποιήσει το e-mail που έχετε δηλώσει.
        /// </summary>
        internal static string UnverifiedEmail1 {
            get {
                return ResourceManager.GetString("UnverifiedEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Για οδηγίες πατήστε.
        /// </summary>
        internal static string UnverifiedEmail2 {
            get {
                return ResourceManager.GetString("UnverifiedEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εδώ.
        /// </summary>
        internal static string UnverifiedEmail3 {
            get {
                return ResourceManager.GetString("UnverifiedEmail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Θα πρέπει να πιστοποιήσετε το e-mail σας για να μπορέσετε να εκτυπώσετε τη Βεβαίωση Συμμετοχής και να χρησιμοποιήσετε την εφαρμογή.
        /// </summary>
        internal static string UnverifiedEmail4 {
            get {
                return ResourceManager.GetString("UnverifiedEmail4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν έχετε ακόμη πιστοποιήσει το λογαριασμό σας. Θα πρέπει να εκτυπώσετε τη Βεβαίωση Συμμετοχής από την καρτέλα.
        /// </summary>
        internal static string UnverifiedUser1 {
            get {
                return ResourceManager.GetString("UnverifiedUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κεντρική Σελίδα.
        /// </summary>
        internal static string UnverifiedUser2 {
            get {
                return ResourceManager.GetString("UnverifiedUser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to και να την αποστείλετε με ΦΑΞ στο Γραφείο Αρωγής για να προχωρήσει στην πιστοποίησή του.
        /// </summary>
        internal static string UnverifiedUser3 {
            get {
                return ResourceManager.GetString("UnverifiedUser3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παράρτημα: {0}.
        /// </summary>
        internal static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο λογαριασμός σας έχει πιστοποιηθεί. Μπορείτε να εκτελέσετε όλες τις λειτουργίες που παρέχονται από το Πληροφοριακό Σύστημα.
        /// </summary>
        internal static string VerifiedUser1 {
            get {
                return ResourceManager.GetString("VerifiedUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αναλυτικές οδηγίες υπάρχουν.
        /// </summary>
        internal static string VerifiedUser2 {
            get {
                return ResourceManager.GetString("VerifiedUser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εδώ.
        /// </summary>
        internal static string VerifiedUser3 {
            get {
                return ResourceManager.GetString("VerifiedUser3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://atlas.grnet.gr/Files/PORTAL_Manual%20FYPA%20App.pdf.
        /// </summary>
        internal static string VerifiedUserUrl {
            get {
                return ResourceManager.GetString("VerifiedUserUrl", resourceCulture);
            }
        }
    }
}
