//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProviderDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProviderDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ProviderDetails", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επειδή ο λογαριασμός έχει πιστοποιηθεί δεν μπορείτε να τροποποιήσετε κάποια από τα στοιχεία σας.&lt;br /&gt;
        ///Για την τροποποίησή τους παρακαλούμε επικοινωνήστε με το Γραφείο Αρωγής στο τηλέφωνο 215 215 7860..
        /// </summary>
        internal static string AccountVerified {
            get {
                return ResourceManager.GetString("AccountVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ενημέρωση Στοιχείων Φορέα.
        /// </summary>
        internal static string ChangeDetails {
            get {
                return ResourceManager.GetString("ChangeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αλλαγή E-mail.
        /// </summary>
        internal static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επαναποστολή E-mail Πιστοποίησης.
        /// </summary>
        internal static string EmailResend {
            get {
                return ResourceManager.GetString("EmailResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στοιχεία Φορέα.
        /// </summary>
        internal static string TabProvider {
            get {
                return ResourceManager.GetString("TabProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στοιχεία Χρήστη.
        /// </summary>
        internal static string TabUser {
            get {
                return ResourceManager.GetString("TabUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα Χρήστη (username):.
        /// </summary>
        internal static string TxtEmail {
            get {
                return ResourceManager.GetString("TxtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;Οι αλλαγές δεν μπορούν να αποθηκευτούν, γιατί υπάρχει ήδη πιστοποιημένος Φορέας Υποδοχής με το Α.Φ.Μ. που δηλώσατε.&lt;br/&gt;Παρακαλούμε επικοινωνήστε με το Γραφείο Αρωγής για να διαπιστωθεί τι συμβαίνει.&lt;br/&gt;.
        /// </summary>
        internal static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σε περίπτωση που θέλετε να επεξεργαστείτε τα στοιχεία που έχουν δηλωθεί, παρακαλώ επικοινωνήστε με τον Κεντρικό Φορέα, ο οποίος δημιούργησε το συγκεκριμένο λογαριασμό χρήστη ({0} , Τηλ.: {1} , E-mail: {2}).
        /// </summary>
        internal static string UpdateNotMaster {
            get {
                return ResourceManager.GetString("UpdateNotMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η ενημέρωση των Στοιχείων του Φορέα Υποδοχής πραγματοποιήθηκε επιτυχώς.
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στοιχεία Χρήστη.
        /// </summary>
        internal static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
    }
}
