//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegistrationInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistrationInput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RegistrationInput", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to γίνεται έλεγχος....
        /// </summary>
        internal static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιβεβαίωση E-mail.
        /// </summary>
        internal static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τα πεδία &apos;E-mail&apos; και &apos;Επιβεβαίωση E-mail&apos; πρέπει να ταιριάζουν.
        /// </summary>
        internal static string EmailConfirmationMatch {
            get {
                return ResourceManager.GetString("EmailConfirmationMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;Επιβεβαίωση E-mail&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string EmailConfirmationValidation {
            get {
                return ResourceManager.GetString("EmailConfirmationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσοχή: Στο e-mail που θα δηλώσετε, θα σας σταλεί το e-mail ενεργοποίησης του λογαριασμού σας. Βεβαιωθείτε ότι το πληκτρολογήσατε σωστά..
        /// </summary>
        internal static string EmailInfo {
            get {
                return ResourceManager.GetString("EmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το Email χρησιμοποιείται.
        /// </summary>
        internal static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το E-mail δεν είναι έγκυρο.
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [έγκυρο e-mail, π.χ. myaccount@myisp.gr ].
        /// </summary>
        internal static string EmailTooltip {
            get {
                return ResourceManager.GetString("EmailTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &apos;E-mail&apos; είναι υποχρεωτικό.
        /// </summary>
        internal static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το κινητό πρέπει να ξεκινάει από 69 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό.
        /// </summary>
        internal static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κωδικός Πρόσβασης (password).
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσοχή: το πλήκτρο Caps Lock είναι πατημένο.
        /// </summary>
        internal static string PasswordCapsWarning {
            get {
                return ResourceManager.GetString("PasswordCapsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιβεβαίωση Κωδικού.
        /// </summary>
        internal static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο Κωδικός Πρόσβασης και η Επιβεβαίωση Κωδικού Πρόσβασης πρέπει να ταιριάζουν.
        /// </summary>
        internal static string PasswordConfirmMatch {
            get {
                return ResourceManager.GetString("PasswordConfirmMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &amp;quot;Επιβεβαίωση Κωδικού Πρόσβασης&amp;quot; είναι υποχρεωτικό.
        /// </summary>
        internal static string PasswordConfirmValidation {
            get {
                return ResourceManager.GetString("PasswordConfirmValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Για τη δική σας ασφάλεια συνιστούμε να επιλέξετε έναν συνδυασμό από γράμματα, αριθμούς ή σύμβολα για να δημιουργήσετε έναν μοναδικό κωδικό πρόσβασης που δεν σχετίζεται με τα προσωπικά σας στοιχεία. Ή, επιλέξτε μια τυχαία λέξη ή φράση και εισαγάγετε λέξεις και αριθμούς στην αρχή, στη μέση και στο τέλος, για να είναι ακόμα πιο δύσκολο να τη μαντέψει κανείς (για παράδειγμα &quot;m1awra1ap3tal0uda&quot;). Η χρήση απλών λέξεων ή φράσεων όπως &quot;password&quot; ή &quot;letmein&quot;, οι ακολουθίες πλήκτρων όπως &quot;qwerty&quot; ή &quot;qazwsx&quot; ή οι ακολ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PasswordInfo {
            get {
                return ResourceManager.GetString("PasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο Κωδικός Πρόσβασης πρέπει να αποτελείται από τουλάχιστον 6 χαρακτήρες.
        /// </summary>
        internal static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιτρέπονται μόνο λατινικοί χαρακτήρες, αριθμητικοί (π.χ. 1,2,3) ή ειδικοί (π.χ. !,@,#)&lt;br/&gt;[τουλάχιστον 6 χαρακτήρες].
        /// </summary>
        internal static string PasswordTooltip {
            get {
                return ResourceManager.GetString("PasswordTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &amp;quot;Κωδικός Πρόσβασης&amp;quot; είναι υποχρεωτικό.
        /// </summary>
        internal static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στοιχεία Λογαριασμού Χρήστη.
        /// </summary>
        internal static string UserDetailsHeader {
            get {
                return ResourceManager.GetString("UserDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα Χρήστη (username).
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το Όνομα Χρήστη χρησιμοποιείται.
        /// </summary>
        internal static string UsernameInUse {
            get {
                return ResourceManager.GetString("UsernameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το Όνομα Χρήστη πρέπει να αποτελείται από τουλάχιστον 5 χαρακτήρες. Επιτρέπονται μόνο λατινικοί χαρακτήρες, αριθμητικοί (π.χ. 1,2) ή ειδικοί (π.χ. _,-,.).
        /// </summary>
        internal static string UsernameInvalid {
            get {
                return ResourceManager.GetString("UsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιτρέπονται μόνο λατινικοί χαρακτήρες, αριθμητικοί (π.χ. 1,2,3) ή ειδικοί (_, - και .)&lt;br/&gt;[τουλάχιστον 5 χαρακτήρες].
        /// </summary>
        internal static string UsernameTooltip {
            get {
                return ResourceManager.GetString("UsernameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πεδίο &amp;quot;Όνομα Χρήστη&amp;quot; είναι υποχρεωτικό.
        /// </summary>
        internal static string UsernameValidation {
            get {
                return ResourceManager.GetString("UsernameValidation", resourceCulture);
            }
        }
    }
}
