ALTER TABLE [dbo].[MassMessageReporterXRef]
    ADD CONSTRAINT [PK_MassMessageReporterXRef_1] PRIMARY KEY CLUSTERED ([ReporterID] ASC, [MassMessageID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

