ALTER TABLE [dbo].[ReporterAcademicXRef]
    ADD CONSTRAINT [PK_ReporterAcademicXRef] PRIMARY KEY CLUSTERED ([ReporterID] ASC, [AcademicID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

