ALTER TABLE [dbo].[SmsLog]
    ADD CONSTRAINT [UQ_SMS_SendID] UNIQUE NONCLUSTERED ([SendID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

