CREATE TABLE [dbo].[InternshipPositionLog] (
    [ID]                             INT            IDENTITY (1, 1) NOT NULL,
    [InternshipPositionID]           INT            NOT NULL,
    [OldStatus]                      INT            NOT NULL,
    [NewStatus]                      INT            NOT NULL,
    [PreAssignedByReporterID]        INT            NULL,
    [PreAssignedByMasterAccountID]   INT            NULL,
    [PreAssignedForAcademicID]       INT            NULL,
    [UnPreAssignedByReporterID]      INT            NULL,
    [UnPreAssignedByMasterAccountID] INT            NULL,
    [AssignedByReporterID]           INT            NULL,
    [AssignedByMasterAccountID]      INT            NULL,
    [AssignedToReporterID]           INT            NULL,
    [ImplementationStartDate]        DATETIME       NULL,
    [ImplementationEndDate]          DATETIME       NULL,
    [UnAssignedByReporterID]         INT            NULL,
    [UnAssignedByMasterAccountID]    INT            NULL,
    [UnAssignedReporterID]           INT            NULL,
    [CompletedByReporterID]          INT            NULL,
    [CompletedByMasterAccountID]     INT            NULL,
    [CompletedAt]                    DATETIME       NULL,
    [CompletionComments]             NVARCHAR (MAX) NULL,
    [CancellationReason]             INT            NOT NULL,
    [UnCompletedByReporterID]        INT            NULL,
    [UnCompletedByMasterAccountID]   INT            NULL,
    [CreatedAt]                      DATETIME       NOT NULL,
    [CreatedAtDateOnly]              DATETIME       NOT NULL,
    [CreatedBy]                      NVARCHAR (50)  NOT NULL
);

