CREATE TABLE [dbo].[Reporter] (
    [ID]                                 INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ReporterType]                       INT            NOT NULL,
    [DeclarationType]                    INT            NOT NULL,
    [ContactName]                        NVARCHAR (200) NULL,
    [ContactPhone]                       NVARCHAR (50)  NULL,
    [ContactMobilePhone]                 NVARCHAR (50)  NULL,
    [ContactEmail]                       NVARCHAR (256) NULL,
    [AlternateContactName]               NVARCHAR (100) NULL,
    [AlternateContactPhone]              NVARCHAR (50)  NULL,
    [AlternateContactMobilePhone]        NVARCHAR (50)  NULL,
    [AlternateContactEmail]              NVARCHAR (256) NULL,
    [Address]                            NVARCHAR (100) NULL,
    [ZipCode]                            NVARCHAR (50)  NULL,
    [CityID]                             INT            NULL,
    [PrefectureID]                       INT            NULL,
    [CountryID]                          INT            NULL,
	[CityText]                           NVARCHAR (200) NULL,	
    [Description]                        NVARCHAR (MAX) NULL,
    [IsMasterAccount]                    BIT            NOT NULL,
    [MasterAccountID]                    INT            NULL,
    [IsApproved]                         BIT            NOT NULL,
    [ProviderType]                       INT            NULL,
    [PrimaryActivityID]                  INT            NULL,
    [ProviderName]                       NVARCHAR (500) NULL,
    [ProviderTradeName]                  NVARCHAR (500) NULL,
    [ProviderAFM]                        NVARCHAR (50)  NULL,
    [ProviderDOY]                        NVARCHAR (256) NULL,
    [ProviderPhone]                      NVARCHAR (50)  NULL,
    [ProviderFax]                        NVARCHAR (10)  NULL,
    [ProviderEmail]                      NVARCHAR (256) NULL,
    [ProviderURL]                        NVARCHAR (256) NULL,
    [ProviderNumberOfEmployees]          INT            NULL,
    [LegalPersonName]                    NVARCHAR (100) NULL,
    [LegalPersonPhone]                   NVARCHAR (100) NULL,
    [LegalPersonEmail]                   NVARCHAR (256) NULL,
    [LegalPersonIdentificationType]      INT            NULL,
    [LegalPersonIdentificationNumber]    NVARCHAR (50)  NULL,
    [LegalPersonIdentificationIssuer]    NVARCHAR (200) NULL,
    [LegalPersonIdentificationIssueDate] DATETIME       NULL,
    [OfficeType]                         INT            NULL,
    [InstitutionID]                      INT            NULL,
    [CertifierType]                      INT            NULL,
    [CertifierName]                      NVARCHAR (100) NULL,
    [CanViewAllAcademics]                BIT            NULL,
    [CanHandleDepartmentalStudents]      BIT            NULL,
    [TransferStudentsToOtherAccount]     BIT            NULL,
    [OriginalFirstName]                  NVARCHAR (100) NULL,
    [OriginalLastName]                   NVARCHAR (100) NULL,
    [IsNameLatin]                        BIT            NULL,
    [GreekFirstName]                     NVARCHAR (100) NULL,
    [GreekLastName]                      NVARCHAR (100) NULL,
    [LatinFirstName]                     NVARCHAR (100) NULL,
    [LatinLastName]                      NVARCHAR (100) NULL,
    [AcademicID]                         INT            NULL,
    [StudentNumber]                      NVARCHAR (50)  NULL,
    [AcademicIDNumber]                   NVARCHAR (12)  NULL,
    [IsAssignedToPosition]               BIT            NULL,
    [UsernameFromLDAP]                   NVARCHAR (100) NOT NULL,
    [UserName]                           NVARCHAR (256) NULL,
    [Email]                              NVARCHAR (256) NULL,
    [IsContactInfoCompleted]             BIT            NOT NULL,
    [IsEmailVerified]                    BIT            NOT NULL,
    [EmailVerificationCode]              NVARCHAR (256) NULL,
    [EmailVerificationDate]              DATETIME       NULL,
    [MustChangePassword]                 BIT            NOT NULL,
    [VerificationStatus]                 INT            NULL,
    [VerificationDate]                   DATETIME       NULL,
    [CertificationNumber]                INT            NULL,
    [CertificationDate]                  DATETIME       NULL,
    [CreatedAt]                          DATETIME       NOT NULL,
    [CreatedAtDateOnly]                  DATETIME       NOT NULL,
    [CreatedBy]                          NVARCHAR (256) NOT NULL,
    [UpdatedAt]                          DATETIME       NULL,
    [UpdatedBy]                          NVARCHAR (256) NULL,
    [ReporterTypeClone]                  AS             ([ReporterType]),
    [RegistrationType]                   INT            NOT NULL, 
    [PositionCount]						 INT NULL, 
    [PreviousAcademicID] INT NULL, 
    [PreviousStudentNumber] NVARCHAR(50) NULL, 
    [IsActive] BIT NOT NULL DEFAULT 1, 
    [AcademicIDStatus] INT NULL, 
    [AcademicIDSubmissionDate] DATETIME NULL, 
	[SMSSentCount] INT NULL, 
    [Language] INT NOT NULL, 
    CONSTRAINT [FK_Reporter_Academic] FOREIGN KEY ([PreviousAcademicID]) REFERENCES [Academic]([ID]) 
);

